### ISSUE TITLE
Cannot resolve method 'get' in 'iterable'

### ISSUE THREAD

**Issue by CrimsonEvenfall** [Loki-Afro/metalarchives#15]
Hi, I'm trying out your library and I'm facing the above error with the example code. In particular, here is the line: 
`Track track = new TrackSearchService(true).getFully(query).get(0);`

**Comment by Loki-Afro** [comment]
Hi there, yes this was changed from a list to an iterable, to "have lazy loading on demand".

i updated the readme, thanks for the hint!
