### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by stenterstal** [Loki-Afro/metalarchives#6]
When performing a new search it throws a NoSuchFieldError.

[Pastelink for better view](https://pastebin.com/xmcx8XNi)

I tried adding the next line to my gradle build file but then it gives me Program type already present errors
`implementation group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5'`

`02-27 18:02:48.929 20122 20122 D AndroidRuntime: Shutting down VM
02-27 18:02:36.948 19801 19801 E AndroidRuntime: FATAL EXCEPTION: main
02-27 18:02:36.948 19801 19801 E AndroidRuntime: Process: com.example.musiclibrary, PID: 19801
02-27 18:02:36.948 19801 19801 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.view.View.performClick(View.java:6669)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:6638)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.view.View.access$3100(View.java:789)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:26145)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6863)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-27 18:02:36.948 19801 19801 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        ... 11 more
02-27 18:02:36.948 19801 19801 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at com.github.loki.afro.metallum.core.util.net.downloader.AbstractDownloader.<clinit>(AbstractDownloader.java:31)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at com.github.loki.afro.metallum.core.util.net.downloader.Downloader.getHTML(Downloader.java:28)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at com.github.loki.afro.metallum.search.AbstractSearchService.parseSearchResults(AbstractSearchService.java:78)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at com.github.loki.afro.metallum.search.AbstractSearchService.performSearch(AbstractSearchService.java:61)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at com.example.musiclibrary.activity_add.getBand(activity_add.java:52)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        at com.example.musiclibrary.activity_add.doSearchAndUpdateResults(activity_add.java:36)
02-27 18:02:36.948 19801 19801 E AndroidRuntime:        ... 13 more
02-27 18:02:48.931 20122 20122 E AndroidRuntime: FATAL EXCEPTION: main
02-27 18:02:48.931 20122 20122 E AndroidRuntime: Process: com.example.musiclibrary, PID: 20122
02-27 18:02:48.931 20122 20122 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.view.View.performClick(View.java:6669)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:6638)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.view.View.access$3100(View.java:789)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:26145)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6863)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-27 18:02:48.931 20122 20122 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        ... 11 more
02-27 18:02:48.931 20122 20122 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at com.github.loki.afro.metallum.core.util.net.downloader.AbstractDownloader.<clinit>(AbstractDownloader.java:31)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at com.github.loki.afro.metallum.core.util.net.downloader.Downloader.getHTML(Downloader.java:28)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at com.github.loki.afro.metallum.search.AbstractSearchService.parseSearchResults(AbstractSearchService.java:78)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at com.github.loki.afro.metallum.search.AbstractSearchService.performSearch(AbstractSearchService.java:61)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at com.example.musiclibrary.activity_add.getBand(activity_add.java:52)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        at com.example.musiclibrary.activity_add.doSearchAndUpdateResults(activity_add.java:36)
02-27 18:02:48.931 20122 20122 E AndroidRuntime:        ... 13 more
02-27 18:02:48.943 20122 20161 D OSTracker: OS Event: crash`

**Comment by Loki-Afro** [comment]
Only a guess, but this lib is not compatible with android :/

If you want I can throw some things around to get a cleaner abstraction . that would it made compatible with android

**Comment by Loki-Afro** [comment]
@stenterstal I replaced apache http client witht he google one

you should have noo problems running this thing on andorid now
